# Generated by Django 4.2.19 on 2025-02-15 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('is_caretaker', models.BooleanField()),
                ('patient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('followers', models.ManyToManyField(to='pillapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medication Name')),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=50, verbose_name='Dosage')),
                ('frequency', models.CharField(choices=[('once', 'Once a day'), ('twice', 'Twice a day'), ('thrice', 'Three times a day'), ('custom', 'Custom')], max_length=10, verbose_name='Frequency')),
                ('first_dose', models.TimeField(blank=True, null=True, verbose_name='First Dose')),
                ('second_dose', models.TimeField(blank=True, null=True, verbose_name='Second Dose')),
                ('quantity', models.IntegerField(help_text='Number of pills', verbose_name='Quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='pillapp.user')),
            ],
        ),
    ]
