# Generated by Django 4.2.19 on 2025-02-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_caretaker',
            field=models.BooleanField(default=False),
        ),
    ]
