# Generated by Django 4.2.19 on 2025-02-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0002_alter_user_is_caretaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, default=None, to='pillapp.user'),
        ),
    ]
