# Generated by Django 4.2.19 on 2025-02-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0004_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
