# Generated by Django 4.2.19 on 2025-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0006_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
