# Generated by Django 4.2.19 on 2025-02-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0007_alter_medication_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='first_dose',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='second_dose',
        ),
        migrations.AddField(
            model_name='medication',
            name='date_prescribed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='directions',
            field=models.TextField(blank=True, default='No directions provided', null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pharmacy_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='pharmacy_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='refills_remaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='frequency',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
