# Generated by Django 4.2.19 on 2025-02-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0008_remove_medication_dosage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='patient_email',
            new_name='caretaker_email',
        ),
    ]
