# Generated by Django 4.2.19 on 2025-02-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0009_rename_patient_email_user_caretaker_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='last_taken',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
