# Generated by Django 4.2.19 on 2025-02-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0010_medication_last_taken'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaretakerVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('caretaker_email', models.EmailField(max_length=254)),
                ('patient_email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
