# Generated by Django 4.2.19 on 2025-02-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0011_caretakerverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_email', models.EmailField(max_length=254)),
                ('caretaker_email', models.EmailField(max_length=254)),
                ('description', models.CharField(blank=True, max_length=2500, null=True)),
            ],
        ),
    ]
