# Generated by Django 4.2.19 on 2025-02-17 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pillapp', '0012_patientlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlog',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
